### ISSUE TITLE
Hello author, ask you some questions about why the package can't create directory, copy, rename

### ISSUE THREAD

**Issue by jiangyong19910326** [tystuyfzand/flysystem-seaweedfs#1]
In the Seaweed file, the reason for the abnormal problems of rename, copy, deleteDir, createDir, listContents and other methods is because of the principle of SeaweedFS, or because you have no time to update. If it is the latter, please tell me how to improve the following, I Willing to continue to improve this package for you

**Comment by tystuyfzand** [comment]
In theory, rename and copy would work. Rename can rename it in the mapper, and copy could download and re-upload the file (though it's quite inefficient).

The implementation doesn't have any knowledge of a directory, rather each file is more like a key/value mapping of name -> seaweedfs file. This means that createDir/deleteDir aren't possible - though some of the other directory operations could be added with some changes to Mapper (including the ability to list a "directory").

The problem is at that point it's likely better to just use the SeaweedFS Filer and have it manage the files without putting a dependency on a cache, database, or other Mapper object.

**Comment by jiangyong19910326** [comment]
> In theory, rename and copy would work. Rename can rename it in the mapper, and copy could download and re-upload the file (though it's quite inefficient).
> 
> The implementation doesn't have any knowledge of a directory, rather each file is more like a key/value mapping of name -> seaweedfs file. This means that createDir/deleteDir aren't possible - though some of the other directory operations could be added with some changes to Mapper (including the ability to list a "directory").
> 
> The problem is at that point it's likely better to just use the SeaweedFS Filer and have it manage the files without putting a dependency on a cache, database, or other Mapper object.

**Comment by jiangyong19910326** [comment]
However, seaweedfs has introduced a new function, filer, which can manage files and directories. Please see if this address is helpful to you and me. https://github.com/chrislusf/seaweedfs/wiki/Directories-and-Files

**Comment by tystuyfzand** [comment]
The intention of this package was to upload files without the use of filer, though I could see a use for a new Filesystem interface that used Filer. I may look into it at some point, but I'm pretty limited on time currently - my best advice is to use the S3 interface built into SeaweedFS and the appropriate Flysystem package for it.
